name: leadsgo_apps
description: Application Marketing Report System.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# version: 1.0.2+2
# version: 1.0.6+6
# version: 1.0.7+7
# version: 1.0.8+8
# version: 1.0.9+9
# version: 1.0.10+10
version: 1.0.11+11

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter_local_notifications: ^8.2.0
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7
  google_nav_bar: ^5.0.5
  colorful_safe_area: ^0.3.0
  device_info: ^2.0.2
  mobile_number: ^1.0.4
  flutter_spinkit: ^5.1.0
  animated_splash_screen: ^1.0.0+1
  simple_animations: ^1.3.3
  carousel_slider: ^2.2.1
  cupertino_icons: ^0.1.2
  date_time_format: ^2.0.1
  datetime_picker_formfield: ^1.0.0
  dropdownfield: ^1.0.3
  flutter:
    sdk: flutter
  flutter_downloader: ^1.6.0
  flutter_full_pdf_viewer: ^1.0.6
  flutter_masked_text: ^0.7.0
  flutter_money_formatter: ^0.8.3
  flutter_signature_pad: ^3.0.0
  flutter_svg: ^0.19.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.0.0
  geolocator: ^7.6.2
  geocoding: ^2.0.1
  # google_fonts: ^1.1.2
  dio: ^4.0.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.0.10
  http: ^0.13.1
  # image_picker:
  image_picker: ^0.8.4+2
  local_auth: any
  material_design_icons_flutter: ^4.0.5955
  # onesignal_flutter: ^3.0.0
  path_provider: ^2.0.5
  # camera: ^0.9.4+1
  camera: ^0.5.8+11
  pdf: ^1.11.0
  permission_handler: any
  photo_view: ^0.10.2
  provider: ^4.0.2
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.8
  toast: ^0.1.5
  url_launcher: ^6.0.12
  video_player: ^2.0.2
  webview_flutter: ^0.3.3

dev_dependencies:
  flutter_launcher_icons: "^0.8.1"
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/leadsgo_icon.png"
  image_path_ios: "assets/leadsgo_icon.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/leadsgo_icon_bg.png"
  adaptive_icon_foreground: "assets/leadsgo_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/menus/
    - assets/
    # - assets/images/pns_aktif.png
    # - assets/images/prapen_5.png
    # - assets/images/prapens_10.png
    # - assets/images/pensiun.png
    # - assets/images/platinum.png

  # Font Family Default Apps LeadsGO
  fonts:
    - family: LeadsGo-Font
      fonts:
        - asset: assets/fonts/SFPro/SF-Pro.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
